
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/hukua.css
- /css/markdown-css.css
- /css/highlight.css

# scripts loaded in the end of the body
scripts:
- https://cdn.bootcss.com/gsap/latest/TweenMax.min.js
- /js/hukua.js
