
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/hukua.css

postStylesheets:
- /css/markdown-css.css
- /css/highlight.css
- https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css

# scripts loaded in the end of the body
scripts:
- https://cdn.bootcss.com/gsap/latest/TweenMax.min.js
- /js/hukua.js

postScripts:
- /js/post.js
- https://cdn1.lncld.net/static/js/3.0.4/av-min.js
- https://unpkg.com/valine/dist/Valine.min.js
